stages:
  - test

variables:
  JULIA_PROJECT: "@."

test:
  stage: test
  image: julia:1.11
  script:
    - julia --project=$JULIA_PROJECT -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
  coverage: '/Test coverage (\d+\.\d+)%/'
  after_script:
    - julia --project=$JULIA_PROJECT -e '
        using Pkg; Pkg.add("Coverage");
        using Coverage;
        c, t = get_summary(process_folder());
        using Printf;
        @printf "Test coverage %.2f%%\n" 100c / t'