name = "PEDDY"
uuid = "0ce30ac1-e258-4977-baf6-e7a1803367e2"
authors = ["Patrick Leibersperger <patrick.leibersperger@slf.ch>", "Patricia Asemann <patriciia.asemann@slf.ch>", "Rainette Engbers <rainette.engbers@slf.ch>"]
version = "0.1.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
