name = "PEDDY"
uuid = "0ce30ac1-e258-4977-baf6-e7a1803367e2"
authors = ["Patrick Leibersperger <patrick.leibersperger@slf.ch>", "Patricia Asemann <patriciia.asemann@slf.ch>", "Rainette Engbers <rainette.engbers@slf.ch>"]
version = "0.1.0-DEV"

[deps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Reexport = "1.2.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
