name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: julia:1.11
    
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: julia --project=@. -e 'ENV["JULIA_SSL_NO_VERIFY_HOSTS"] = "pkg.julialang.org,github.com"; using Pkg; Pkg.instantiate()'
    
    - name: Run tests with coverage
      run: julia --project=@. -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
    
    - name: Print test coverage
      run: |
        julia --project=@. -e '
          using Pkg; Pkg.add("Coverage");
          using Coverage;
          coverage = process_folder();
          covered_lines, total_lines = get_summary(coverage);
          using Printf;
          percentage = round(100 * covered_lines / total_lines, digits=1);
          @printf "Test coverage: %.1f%% (%d/%d lines)\n" percentage covered_lines total_lines'
        